### ISSUE TITLE
Suggestion - provide an example how to test telegram commands

### ISSUE THREAD

**Issue by kubk** [BoShurik/telegram-bot-example#1]
It would be nice to have an example how to test telegram commands using PHPUnit/Behat.

**Comment by BoShurik** [comment]
Something like this: https://github.com/BoShurik/TelegramBotBundle/blob/master/tests/Telegram/Command/HelpCommandTest.php

**Comment by kubk** [comment]
@BoShurik Thanks, this is what I need.
